// ============================================================
//  BioMarina — Mock Data
//  Especies del Caribe Colombiano (datos representativos)
// ============================================================

import type { Especie, EstadisticasCatalogo } from '@/shared/types/especie'

export const MOCK_ESPECIES: Especie[] = [
  {
    id: '1',
    nombreComun: 'Pez León Rojo',
    nombreComunAlt: ['Pez Escorpión', 'Lionfish'],
    nombreCientifico: 'Pterois volitans',
    emoji: '🦁',
    descripcionGeneral: 'Especie invasora procedente del Indo-Pacífico. Altamente voraz y sin depredadores naturales en el Caribe, representa una grave amenaza para los arrecifes del Caribe colombiano. Su veneno en las espinas dorsales puede causar dolor intenso en humanos.',
    curiosidades: [
      'Una hembra puede liberar hasta 30,000 huevos cada 4 días.',
      'Reduce hasta un 79% las poblaciones de peces juveniles de arrecife en zonas invadidas.',
      'El veneno es doloroso pero rara vez letal para humanos.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Chordata', clase: 'Actinopterygii', orden: 'Scorpaeniformes', familia: 'Scorpaenidae', genero: 'Pterois', especie: 'volitans' },
    biologia: { pesoPromedioKg: 0.3, pesoMaximoKg: 1.0, longPromedCm: 30, longMaxCm: 47, dieta: ['Peces pequeños', 'Crustáceos', 'Camarones'], nivelTrofico: 4.2, reproduccion: 'ovíparo', migracion: false, longevidadAnios: 15 },
    habitat: { tipo: 'arrecife', profundidadMinM: 1, profundidadMaxM: 55, tempMinC: 22, tempMaxC: 30, salinidadPpt: 35, sustrato: ['coral', 'roca', 'arena'] },
    conservacion: { uicn: 'LC', uicnAnio: 2020, vedaTipo: 'ninguna', valorEcologico: 'muy alto', protegida: false, notasLegales: 'Programa de control activo por INVEMAR. Se recomienda su captura y consumo.' },
    pesca: { valorComercial: 'medio', capturaAnualTon: 12, artesanal: true, industrial: false, acuariofilia: false, artesPesca: ['buceo con lanza', 'trampas'], puertosPrincipales: ['Santa Marta', 'Cartagena'] },
    zonas: [
      { nombre: 'Parque Tayrona', departamento: 'Magdalena', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-73.9, 11.3] } },
      { nombre: 'Islas del Rosario', departamento: 'Bolívar', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-75.8, 10.2] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Pterois_volitans_Manado-e.jpg/1280px-Pterois_volitans_Manado-e.jpg', esPrincipal: true, licencia: 'CC BY-SA 3.0' },
    ],
    estado: 'publicado', completitud: 92, publicadoEn: '2024-01-15T00:00:00Z', createdAt: '2024-01-10T00:00:00Z',
  },
  {
    id: '2',
    nombreComun: 'Tiburón Ballena',
    nombreComunAlt: ['Whale Shark'],
    nombreCientifico: 'Rhincodon typus',
    emoji: '🦈',
    descripcionGeneral: 'El pez más grande del mundo. Filtrando plancton en las aguas cálidas del Caribe colombiano, es un indicador clave de salud oceánica. Sus avistamientos frente a La Guajira son cada vez más frecuentes.',
    curiosidades: [
      'Puede alcanzar hasta 18 metros de longitud.',
      'A pesar de su tamaño, se alimenta únicamente de plancton y pequeños peces.',
      'Cada individuo tiene un patrón de puntos único, como una huella digital.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Chordata', clase: 'Chondrichthyes', orden: 'Orectolobiformes', familia: 'Rhincodontidae', genero: 'Rhincodon', especie: 'typus' },
    biologia: { pesoPromedioKg: 12000, pesoMaximoKg: 21500, longPromedCm: 900, longMaxCm: 1880, dieta: ['Plancton', 'Krill', 'Huevos de peces'], nivelTrofico: 2.0, reproduccion: 'ovovivíparo', migracion: true, longevidadAnios: 130 },
    habitat: { tipo: 'pelagico', profundidadMinM: 0, profundidadMaxM: 1900, tempMinC: 21, tempMaxC: 30, salinidadPpt: 35 },
    conservacion: { uicn: 'EN', uicnAnio: 2022, vedaTipo: 'prohibida', valorEcologico: 'muy alto', protegida: true, notasLegales: 'Captura completamente prohibida en Colombia (Resolución MADS 1032/2016). Pena de cárcel hasta 5 años.' },
    pesca: { valorComercial: 'ninguno', artesanal: false, industrial: false, acuariofilia: false },
    zonas: [
      { nombre: 'La Guajira', departamento: 'La Guajira', tipo: 'pelagico', punto: { type: 'Point', coordinates: [-72.2, 12.1] } },
      { nombre: 'Providencia', departamento: 'Archipiélago de San Andrés', tipo: 'pelagico', punto: { type: 'Point', coordinates: [-81.4, 13.3] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Rhincodon_typus_-_Aquarium_finBack.jpg/1280px-Rhincodon_typus_-_Aquarium_finBack.jpg', esPrincipal: true, licencia: 'CC BY 3.0' },
    ],
    estado: 'publicado', completitud: 88, publicadoEn: '2024-02-01T00:00:00Z', createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '3',
    nombreComun: 'Tortuga Carey',
    nombreComunAlt: ['Tortuga Pico de Halcón', 'Hawksbill Turtle'],
    nombreCientifico: 'Eretmochelys imbricata',
    emoji: '🐢',
    descripcionGeneral: 'La tortuga carey es fundamental para la salud de los arrecifes de coral del Caribe, ya que se alimenta principalmente de esponjas, controlando su crecimiento y manteniendo la diversidad del arrecife.',
    curiosidades: [
      'Su concha tiene un patrón de escamas solapadas únicas entre las tortugas marinas.',
      'Se orienta magnéticamente para regresar a la playa donde nació a poner huevos.',
      'El tráfico ilegal de su concha ("carey") fue la principal causa de su declive histórico.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Chordata', clase: 'Reptilia', orden: 'Testudines', familia: 'Cheloniidae', genero: 'Eretmochelys', especie: 'imbricata' },
    biologia: { pesoPromedioKg: 80, pesoMaximoKg: 127, longPromedCm: 80, longMaxCm: 95, dieta: ['Esponjas', 'Medusas', 'Moluscos'], nivelTrofico: 2.5, reproduccion: 'ovíparo', migracion: true, longevidadAnios: 50 },
    habitat: { tipo: 'arrecife', profundidadMinM: 1, profundidadMaxM: 20, tempMinC: 24, tempMaxC: 32, sustrato: ['coral', 'roca'] },
    conservacion: { uicn: 'CR', uicnAnio: 2022, vedaTipo: 'permanente', vedaMeses: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Noviembre', 'Diciembre'], valorEcologico: 'muy alto', protegida: true, notasLegales: 'Especie estrictamente protegida por CITES Apéndice I. Captura, tenencia o comercio es delito penal en Colombia.' },
    pesca: { valorComercial: 'ninguno', artesanal: false, industrial: false, acuariofilia: false },
    zonas: [
      { nombre: 'Parque Tayrona', departamento: 'Magdalena', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-73.9, 11.3] } },
      { nombre: 'Islas de San Bernardo', departamento: 'Sucre', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-75.9, 9.8] } },
      { nombre: 'San Andrés', departamento: 'Archipiélago de San Andrés', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-81.7, 12.5] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Pemuteran_Bay_Hawksbill_turtle.jpg/1280px-Pemuteran_Bay_Hawksbill_turtle.jpg', esPrincipal: true, licencia: 'CC BY-SA 3.0' },
    ],
    estado: 'publicado', completitud: 95, publicadoEn: '2024-01-20T00:00:00Z', createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '4',
    nombreComun: 'Pargo Rojo',
    nombreComunAlt: ['Red Snapper', 'Huachinango'],
    nombreCientifico: 'Lutjanus campechanus',
    emoji: '🐟',
    descripcionGeneral: 'Uno de los peces más importantes para la pesca artesanal e industrial del Caribe colombiano. Su sobreexplotación en las últimas décadas ha reducido significativamente sus poblaciones en la plataforma continental.',
    curiosidades: [
      'Puede vivir hasta 57 años.',
      'Los adultos forman grandes agregaciones reproductivas en luna llena.',
      'Es uno de los peces tropicales más comercialmente valiosos del mundo.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Chordata', clase: 'Actinopterygii', orden: 'Perciformes', familia: 'Lutjanidae', genero: 'Lutjanus', especie: 'campechanus' },
    biologia: { pesoPromedioKg: 4, pesoMaximoKg: 22, longPromedCm: 60, longMaxCm: 100, dieta: ['Crustáceos', 'Pequeños peces', 'Calamares'], nivelTrofico: 3.8, reproduccion: 'ovíparo', migracion: false, longevidadAnios: 57 },
    habitat: { tipo: 'fondo', profundidadMinM: 10, profundidadMaxM: 200, tempMinC: 20, tempMaxC: 28, sustrato: ['arena', 'roca', 'coral'] },
    conservacion: { uicn: 'VU', uicnAnio: 2021, vedaTipo: 'temporal', vedaMeses: ['Abril', 'Mayo'], valorEcologico: 'alto', protegida: false, notasLegales: 'Talla mínima de captura: 30 cm. Veda reproductiva Abril-Mayo por resolución AUNAP.' },
    pesca: { valorComercial: 'muy alto', capturaAnualTon: 4500, artesanal: true, industrial: true, acuariofilia: false, artesPesca: ['palangre', 'red de enmalle', 'anzuelo'], puertosPrincipales: ['Barranquilla', 'Santa Marta', 'Cartagena', 'Tolú'] },
    zonas: [
      { nombre: 'Plataforma de Santa Marta', departamento: 'Magdalena', tipo: 'fondo', punto: { type: 'Point', coordinates: [-74.5, 11.0] } },
      { nombre: 'Golfo de Morrosquillo', departamento: 'Sucre', tipo: 'costero', punto: { type: 'Point', coordinates: [-75.7, 9.3] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Red_snapper_opelousas.jpg/1280px-Red_snapper_opelousas.jpg', esPrincipal: true, licencia: 'Public Domain' },
    ],
    estado: 'publicado', completitud: 85, completudMedia: 85, publicadoEn: '2024-02-10T00:00:00Z', createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '5',
    nombreComun: 'Manta Raya Gigante',
    nombreComunAlt: ['Giant Oceanic Manta Ray', 'Manta'],
    nombreCientifico: 'Mobula birostris',
    emoji: '🪁',
    descripcionGeneral: 'La manta raya gigante es el pez de aleta más grande del mundo y uno de los animales más inteligentes del océano. Habitual en aguas abiertas del Caribe colombiano, son fundamentales como indicadores de ecosistemas saludables.',
    curiosidades: [
      'Tiene el cerebro más grande de todos los peces, con una relación cerebro/cuerpo similar a la de los mamíferos.',
      'Puede saltar fuera del agua varios metros de altura.',
      'Se reúne en grupos de cientos para limppiarse en estaciones de limpieza.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Chordata', clase: 'Chondrichthyes', orden: 'Myliobatiformes', familia: 'Mobulidae', genero: 'Mobula', especie: 'birostris' },
    biologia: { pesoPromedioKg: 1400, pesoMaximoKg: 3000, longPromedCm: 600, longMaxCm: 900, dieta: ['Zooplancton', 'Krill', 'Pequeños peces'], nivelTrofico: 2.2, reproduccion: 'ovovivíparo', migracion: true, longevidadAnios: 50 },
    habitat: { tipo: 'pelagico', profundidadMinM: 0, profundidadMaxM: 1000, tempMinC: 23, tempMaxC: 30 },
    conservacion: { uicn: 'EN', uicnAnio: 2019, vedaTipo: 'prohibida', valorEcologico: 'muy alto', protegida: true, notasLegales: 'Protegida bajo CITES Apéndice II. Captura prohibida en Colombia desde 2007 (Res. 1531 MADS).' },
    pesca: { valorComercial: 'ninguno', artesanal: false, industrial: false, acuariofilia: false },
    zonas: [
      { nombre: 'La Guajira (Bahía Portete)', departamento: 'La Guajira', tipo: 'pelagico', punto: { type: 'Point', coordinates: [-71.9, 12.5] } },
      { nombre: 'Providencia', departamento: 'Archipiélago de San Andrés', tipo: 'pelagico', punto: { type: 'Point', coordinates: [-81.4, 13.3] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Manta_birostris-Thailand4.jpg/1280px-Manta_birostris-Thailand4.jpg', esPrincipal: true, licencia: 'CC BY-SA 2.0' },
    ],
    estado: 'publicado', completitud: 90, publicadoEn: '2024-03-01T00:00:00Z', createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: '6',
    nombreComun: 'Caballito de Mar Occidental',
    nombreComunAlt: ['Seahorse', 'Caballito Lonchanero'],
    nombreCientifico: 'Hippocampus reidi',
    emoji: '🐴',
    descripcionGeneral: 'El caballito de mar largo (o Reidi) habita principalmente en lechos de pastos marinos y manglares del Caribe colombiano. Es una especie indicadora de la salud de estos ecosistemas costeros críticos.',
    curiosidades: [
      'El macho es quien carga y da a luz a las crías.',
      'Se camuflan cambiando de color instantáneamente.',
      'Pueden morir si son separados de su pareja monógama.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Chordata', clase: 'Actinopterygii', orden: 'Syngnathiformes', familia: 'Syngnathidae', genero: 'Hippocampus', especie: 'reidi' },
    biologia: { pesoPromedioKg: 0.01, longPromedCm: 15, longMaxCm: 20, dieta: ['Artemia', 'Copépodos', 'Pequeños crustáceos'], nivelTrofico: 3.1, reproduccion: 'ovovivíparo', migracion: false, longevidadAnios: 5 },
    habitat: { tipo: 'manglar', profundidadMinM: 0, profundidadMaxM: 10, tempMinC: 23, tempMaxC: 30, sustrato: ['pastos marinos', 'coral', 'algas'] },
    conservacion: { uicn: 'DD', uicnAnio: 2017, vedaTipo: 'permanente', valorEcologico: 'alto', protegida: true, notasLegales: 'Incluido en Apéndice II de CITES. Comercio internacional regulado por cuotas de exportación.' },
    pesca: { valorComercial: 'bajo', artesanal: false, industrial: false, acuariofilia: true, artesPesca: ['redes de arrastre (captura incidental)'] },
    zonas: [
      { nombre: 'Ciénaga Grande de Santa Marta', departamento: 'Magdalena', tipo: 'estuario', punto: { type: 'Point', coordinates: [-74.4, 10.7] } },
      { nombre: 'Golfo de Urabá (Manglar)', departamento: 'Antioquia', tipo: 'manglar', punto: { type: 'Point', coordinates: [-76.8, 8.3] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Hippocampus_reidi%2C_Bonaire.jpg/800px-Hippocampus_reidi%2C_Bonaire.jpg', esPrincipal: true, licencia: 'CC BY-SA 2.0' },
    ],
    estado: 'publicado', completitud: 72, publicadoEn: '2024-03-10T00:00:00Z', createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '7',
    nombreComun: 'Tiburón Ballena de Arrecife',
    nombreComunAlt: ['Caribbean Reef Shark', 'Tiburón de Arrecife'],
    nombreCientifico: 'Carcharhinus perezi',
    emoji: '🦈',
    descripcionGeneral: 'El tiburón de arrecife del Caribe es un depredador ápex fundamental en el ecosistema del arrecife coralino. Su presencia regula las poblaciones de peces medianos y es un indicador crítico de arrecifes saludables.',
    curiosidades: [
      'Puede entrar en un estado de trance llamado "tónico inmovilidad" si se le voltea.',
      'Crucial para mantener el equilibrio trófico de los arrecifes del Caribe.',
      'Suele comerse los peces heridos, actuando como "sanador" del arrecife.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Chordata', clase: 'Chondrichthyes', orden: 'Carcharhiniformes', familia: 'Carcharhinidae', genero: 'Carcharhinus', especie: 'perezi' },
    biologia: { pesoPromedioKg: 70, pesoMaximoKg: 150, longPromedCm: 200, longMaxCm: 300, dieta: ['Peces teleósteos', 'Cefalópodos', 'Crustáceos'], nivelTrofico: 4.5, reproduccion: 'vivíparo', migracion: false, longevidadAnios: 25 },
    habitat: { tipo: 'arrecife', profundidadMinM: 1, profundidadMaxM: 200, tempMinC: 22, tempMaxC: 30, sustrato: ['coral', 'roca'] },
    conservacion: { uicn: 'EN', uicnAnio: 2021, vedaTipo: 'prohibida', valorEcologico: 'muy alto', protegida: true, notasLegales: 'Protegido bajo el Plan de Acción Nacional para Conservación de Tiburones Colombia (PAN-Tiburones).' },
    pesca: { valorComercial: 'bajo', capturaAnualTon: 45, artesanal: true, industrial: false, acuariofilia: false, artesPesca: ['palangre', 'red (incidental)'], puertosPrincipales: ['Tolú', 'Santa Marta'] },
    zonas: [
      { nombre: 'Islas del Rosario', departamento: 'Bolívar', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-75.8, 10.2] } },
      { nombre: 'Providencia', departamento: 'Archipiélago de San Andrés', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-81.4, 13.3] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Caribbean_reef_shark.jpg/1280px-Caribbean_reef_shark.jpg', esPrincipal: true, licencia: 'CC BY-SA 3.0' },
    ],
    estado: 'publicado', completitud: 88, publicadoEn: '2024-03-15T00:00:00Z', createdAt: '2024-03-10T00:00:00Z',
  },
  {
    id: '8',
    nombreComun: 'Coral Cuerno de Ciervo',
    nombreComunAlt: ['Staghorn Coral', 'Acropora'],
    nombreCientifico: 'Acropora cervicornis',
    emoji: '🪸',
    descripcionGeneral: 'Uno de los corales constructores de arrecifes más importantes del Caribe. Ha sufrido un declive superior al 80% en los últimos 30 años debido al blanqueamiento por aumento de temperatura y la enfermedad de pérdida de tejido de coral duro.',
    curiosidades: [
      'Puede crecer hasta 10 cm por año, siendo uno de los corales de crecimiento más rápido.',
      'Proporciona hábitat estructural para cientos de otras especies marinas.',
      'Está siendo objeto de proyectos piloto de trasplante y restauración en todo el Caribe.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Cnidaria', clase: 'Anthozoa', orden: 'Scleractinia', familia: 'Acroporidae', genero: 'Acropora', especie: 'cervicornis' },
    biologia: { dieta: ['Zooplancton', 'Algas simbióticas (zooxantelas)'], nivelTrofico: 1.0, reproduccion: 'ovíparo', migracion: false },
    habitat: { tipo: 'arrecife', profundidadMinM: 1, profundidadMaxM: 20, tempMinC: 25, tempMaxC: 29, salinidadPpt: 35, sustrato: ['sustrato duro'] },
    conservacion: { uicn: 'CR', uicnAnio: 2022, vedaTipo: 'prohibida', valorEcologico: 'muy alto', protegida: true, notasLegales: 'En peligro crítico. Prohibida cualquier extracción, daño o comercialización bajo la Ley de Pesca colombiana.' },
    pesca: { valorComercial: 'ninguno', artesanal: false, industrial: false, acuariofilia: false },
    zonas: [
      { nombre: 'Parque Tayrona', departamento: 'Magdalena', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-73.9, 11.3] } },
      { nombre: 'Islas del Rosario', departamento: 'Bolívar', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-75.8, 10.2] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Acropora_cervicornis.jpg/1280px-Acropora_cervicornis.jpg', esPrincipal: true, licencia: 'Public Domain' },
    ],
    estado: 'publicado', completitud: 80, publicadoEn: '2024-04-01T00:00:00Z', createdAt: '2024-03-20T00:00:00Z',
  },
  {
    id: '9',
    nombreComun: 'Langosta Espinosa del Caribe',
    nombreComunAlt: ['Caribbean Spiny Lobster', 'Langosta'],
    nombreCientifico: 'Panulirus argus',
    emoji: '🦞',
    descripcionGeneral: 'La langosta espinosa es el crustáceo de mayor valor comercial en el Caribe colombiano, especialmente en San Andrés y Providencia. Su manejo sostenible es crítico para maintener los medios de vida de comunidades costeras.',
    curiosidades: [
      'Migra en procesión de hasta varios cientos de individuos formando largas filas.',
      'No tiene pinzas pero sus antenas pueden ser más largas que todo su cuerpo.',
      'Puede detectar cambios en la corriente oceánica con sus quimiorreceptores.',
    ],
    taxonomia: { reino: 'Animalia', filo: 'Arthropoda', clase: 'Malacostraca', orden: 'Decapoda', familia: 'Palinuridae', genero: 'Panulirus', especie: 'argus' },
    biologia: { pesoPromedioKg: 1.5, pesoMaximoKg: 5.0, longPromedCm: 40, longMaxCm: 60, dieta: ['Moluscos', 'Gusanos marinos', 'Equinodermos'], nivelTrofico: 3.4, reproduccion: 'ovíparo', migracion: true, longevidadAnios: 20 },
    habitat: { tipo: 'arrecife', profundidadMinM: 1, profundidadMaxM: 90, tempMinC: 22, tempMaxC: 30, sustrato: ['coral', 'roca', 'arena'] },
    conservacion: { uicn: 'LC', uicnAnio: 2019, vedaTipo: 'temporal', vedaMeses: ['Abril', 'Mayo', 'Junio', 'Julio'], valorEcologico: 'alto', protegida: false, notasLegales: 'Veda reproductiva Abr-Jul en San Andrés. Talla mínima: 7.5 cm de cefalotórax. Hembras ovadas no se pueden capturar.' },
    pesca: { valorComercial: 'muy alto', capturaAnualTon: 850, artesanal: true, industrial: false, acuariofilia: false, artesPesca: ['buceo en apnea', 'nasas', 'buceo autónomo'], puertosPrincipales: ['San Andrés', 'Providencia', 'Santa Marta'] },
    zonas: [
      { nombre: 'San Andrés', departamento: 'Archipiélago de San Andrés', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-81.7, 12.5] } },
      { nombre: 'Providencia', departamento: 'Archipiélago de San Andrés', tipo: 'arrecife', punto: { type: 'Point', coordinates: [-81.4, 13.3] } },
    ],
    media: [
      { tipo: 'foto', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Caribbean,_spiny,_lobster.jpg/1280px-Caribbean,_spiny,_lobster.jpg', esPrincipal: true, licencia: 'CC BY 2.0' },
    ],
    estado: 'publicado', completitud: 95, publicadoEn: '2024-04-15T00:00:00Z', createdAt: '2024-04-01T00:00:00Z',
  },
]

export const MOCK_ESTADISTICAS: EstadisticasCatalogo = {
  totalEspecies: 284,
  publicadas: 187,
  enPeligro: 34,
  vulnerables: 52,
  protegidas: 89,
  completitudMedia: 84,
  porHabitat: [
    { habitat: 'arrecife', total: 142 },
    { habitat: 'pelagico', total: 56 },
    { habitat: 'fondo', total: 38 },
    { habitat: 'manglar', total: 24 },
    { habitat: 'estuario', total: 16 },
    { habitat: 'costero', total: 8 },
  ],
  porUICN: [
    { uicn: 'LC', total: 120 },
    { uicn: 'NT', total: 45 },
    { uicn: 'VU', total: 52 },
    { uicn: 'EN', total: 28 },
    { uicn: 'CR', total: 14 },
    { uicn: 'DD', total: 18 },
    { uicn: 'NE', total: 7 },
  ],
}
